#ifndef __CONST_H
#define __CONST_H

#define CST_CONSOLE_TX_MAX_STRING_LENGTH 128
#define CST_MASTER_RX_MAX_STRING_LENGTH   16
#define CST_MASTER_TX_MAX_STRING_LENGTH   CST_MASTER_RX_MAX_STRING_LENGTH
#define CST_STRING_FIFO_MAX_STRING_LENGTH CST_MASTER_RX_MAX_STRING_LENGTH

#define CST_STRING_FIFO_MAX_ELEMENTS      10
#define CST_UART_TRANSMIT_TIMEOUT_IN_MS 1000

#endif /* __CONST_H */
