#ifndef __CONST_H
#define __CONST_H

#define CST_FRONT_RIGHT_WHEEL_NAME "FRONT RIGHT"
#define CST_FRONT_LEFT_WHEEL_NAME  "FRONT LEFT "
#define CST_REAR_LEFT_WHEEL_NAME   "REAR  LEFT "
#define CST_REAR_RIGHT_WHEEL_NAME  "REAR  RIGHT"

#define CST_CONSOLE_TX_MAX_STRING_LENGTH  128
#define CST_MASTER_TX_MAX_STRING_LENGTH    CST_CONSOLE_TX_MAX_STRING_LENGTH
#define CST_MASTER_VELOCITY_STRING_LENGTH  21
#define CST_MASTER_RX_MAX_STRING_LENGTH    20
#define CST_STRING_FIFO_MAX_STRING_LENGTH CST_MASTER_RX_MAX_STRING_LENGTH

#define CST_CIRCULAR_BUFFER_MAX_ELEMENTS  10
#define CST_STRING_FIFO_MAX_ELEMENTS      10
#define CST_UART_TRANSMIT_TIMEOUT_IN_MS 1000

#endif /* __CONST_H */
