#ifndef __SETUP_H
#define __SETUP_H

#include "log.h"
#include "main.h"

#define STP_DEFAULT_IS_LOG_ON    true
#define STP_DEFAULT_LOG_LEVEL    LOG_LEVEL_DEBUG
#define STP_DEFAULT_PRINT_OUTPUT MAIN_PRINT_OUTPUT_TO_CONSOLE

#define STP_PAD_BUTTONS_DEBOUNCE_PERIOD_IN_S 2

#define STP_CONSOLE_MIN_SPEED   0
#define STP_CONSOLE_MAX_SPEED 100
#define STP_DRIVE_MIN_SPEED     0
#define STP_DRIVE_MAX_SPEED    40

#endif /* __SETUP_H */
